version: '3.8'

services:

  # ─────────────────────────────
  # PostgreSQL
  # ─────────────────────────────
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always

    environment:
      POSTGRES_USER: shahbaz_admin
      POSTGRES_PASSWORD: shahbaz_password
      POSTGRES_DB: smartwell_db

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - smartwell_net

  # ─────────────────────────────
  # MQTT Broker
  # ─────────────────────────────
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto_broker
    restart: always

    ports:
      - "1883:1883"

    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

    networks:
      - smartwell_net

  # ─────────────────────────────
  # FastAPI Backend
  # ─────────────────────────────
  backend:
    image: shahbazzulfiqar/smartwell:latest
    container_name: fastapi_backend
    restart: always

    ports:
      - "8000:8080"

    depends_on:
      - db
      - mosquitto

    environment:

      # DATABASE
      DATABASE_URL: postgresql://shahbaz_admin:shahbaz_password@db:5432/smartwell_db

      # JWT
      JWT_SECRET_KEY: your_super_secret_key

      # MQTT
      MQTT_BROKER: mosquitto
      MQTT_PORT: 1883
      MQTT_KEEPALIVE: 60

      MQTT_USERNAME: ""
      MQTT_PASSWORD: ""

      MQTT_QOS: 1

      MQTT_COMMAND_TOPIC_PREFIX: tubewell

      MQTT_TELEMETRY_TOPIC_PREFIX: tubewell
      MQTT_TELEMETRY_TOPIC_SUFFIX: telemetry

    networks:
      - smartwell_net

networks:
  smartwell_net:
    driver: bridge

volumes:
  postgres_data: