# app/schemas/device_schema.py
#
# Pydantic schemas for Device endpoints.
#
# ── Design Notes ──────────────────────────────────────────────────────────────
#  • device_secret is generated server-side (secrets.token_urlsafe) and is
#    NEVER accepted from the request body — removed from DeviceCreate.
#  • device_secret is NEVER returned in responses — removed from DeviceResponse.
#    If the ESP32 needs it, create a separate protected endpoint for that only.
#  • id is NOT in DeviceCreate — the service sets id = device_uid internally.
# ──────────────────────────────────────────────────────────────────────────────

from pydantic import BaseModel
from datetime import datetime
from typing import Optional
from uuid import UUID


# ─────────────────────────────────────────────────────────────────────────────
# CREATE
# ─────────────────────────────────────────────────────────────────────────────
class DeviceCreate(BaseModel):
    """
    Fields accepted from the client when registering a new device.

    Excluded fields (set server-side):
    - id            → set to device_uid by DeviceService
    - device_secret → generated by secrets.token_urlsafe(32) in DeviceService
    - user_id       → set from JWT token, never from request body
    """
    device_name : str
    device_uid  : str                    # used as the primary key (e.g. TW-DEV-0001)
    sim_number  : Optional[str] = None
    location    : Optional[str] = None


# ─────────────────────────────────────────────────────────────────────────────
# UPDATE
# ─────────────────────────────────────────────────────────────────────────────
class DeviceUpdate(BaseModel):
    """
    Fields the client may update on an existing device.
    All fields are optional — only provided fields are changed.
    """
    device_name   : Optional[str]   = None
    sim_number    : Optional[str]   = None
    location      : Optional[str]   = None
    reference_freq: Optional[float] = None
   
    


# ─────────────────────────────────────────────────────────────────────────────
# RESPONSE
# ─────────────────────────────────────────────────────────────────────────────
class DeviceResponse(BaseModel):
    """
    Fields returned to the client after create / update / get.

    Excluded fields (never exposed):
    - device_secret → sensitive credential used by the ESP32 only.
                      Expose via a separate secured endpoint if needed.
    """
    id          : str
    user_id     : UUID
    device_name : str
    device_uid  : str
    sim_number  : Optional[str]
    location    : Optional[str]
    created_at  : Optional[datetime]
   

    class Config:
        from_attributes = True